/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seabattle.ui;

import java.awt.event.KeyEvent;
import seabattle.model.ComputerPlayer;
import seabattle.model.GameModel;
import seabattle.model.HumanPlayer;
import seabattle.model.ObjectSet;

/**
 *
 * @author anton
 */
public class ArangeShips extends javax.swing.JFrame {

    private GameModel _gameModel;
    private boolean _firstRanged;
    
    /**
     * Creates new form ArangeShips
     */
    public ArangeShips(){        
        
        _gameModel = new GameModel(new HumanPlayer(), 
                        new ComputerPlayer(10, 10), 10, 10);
        
        
        _firstRanged = false;
        initComponents();
        
        seaAreaPanel.setObjectSet(new ObjectSet(_gameModel.getActiveSeaArea()));
        seaAreaPanel.setSeaArea(_gameModel.getActiveSeaArea());
        //seaAreaPanel.repaint();
        this.setSize(seaAreaPanel.getSize().width + 20, seaAreaPanel.getSize().height + 80);
        addKeyListener(seaAreaPanel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seaAreaPanel = new seabattle.ui.ArangeShipsFieldPanel(_gameModel.getActiveSeaArea().height(), _gameModel.getActiveSeaArea().width());
        okButton = new javax.swing.JButton();
        playerName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 193, 255));
        setMinimumSize(new java.awt.Dimension(513, 371));

        seaAreaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seaAreaPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seaAreaPanelLayout = new javax.swing.GroupLayout(seaAreaPanel);
        seaAreaPanel.setLayout(seaAreaPanelLayout);
        seaAreaPanelLayout.setHorizontalGroup(
            seaAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seaAreaPanelLayout.setVerticalGroup(
            seaAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        okButton.setText("Готов");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        playerName.setText("Игрок 1");
        playerName.setName(""); // NOI18N
        playerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                playerNameKeyPressed(evt);
            }
        });

        jLabel6.setText("Имя игрока");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seaAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addGap(60, 60, 60)
                        .addComponent(playerName, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(125, 125, 125)
                        .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seaAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if (!_firstRanged) {
            _gameModel.getActivePlayer().setName(playerName.getText());
            if (seaAreaPanel.isDone()) {
                _firstRanged = true;
                if (_gameModel.getPassivePlayer().getClass() == HumanPlayer.class) {
                    playerName.setText("Игрок 2");
                    seaAreaPanel.setObjectSet(new ObjectSet(_gameModel.getPassiveSeaArea()));
                    seaAreaPanel.setSeaArea(_gameModel.getPassiveSeaArea());
                    seaAreaPanel.repaint();
                } else {
                    ComputerPlayer com = (ComputerPlayer)_gameModel.getPassivePlayer();
                    com.rangeObjectsOnSea(_gameModel.getPassiveSeaArea());
                    
                    Battle tmp = new Battle(this, _gameModel);
                    tmp.setVisible(true);
                    this.setVisible(false);
                    tmp.requestFocus();
                    tmp.requestFocusInWindow();
                    this.dispose();
                }
            }
        } else  if (seaAreaPanel.isDone()){
            // arrange done
            _gameModel.getPassivePlayer().setName(playerName.getText());
            Battle tmp = new Battle(this, _gameModel);
            tmp.setVisible(true);
            this.setVisible(false);
            tmp.requestFocus();
            tmp.requestFocusInWindow();
            this.dispose();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void playerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerNameKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (!_firstRanged) {
                    _gameModel.getActivePlayer().setName(playerName.getText());
                } else {
                    _gameModel.getPassivePlayer().setName(playerName.getText());
                }
                seaAreaPanel.requestFocus();
                break;
        }
    }//GEN-LAST:event_playerNameKeyPressed

    private void seaAreaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seaAreaPanelMouseClicked
        // TODO add your handling code here:
        if (playerName.isFocusOwner()) {
            this.requestFocus();
        }
    }//GEN-LAST:event_seaAreaPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArangeShips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArangeShips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArangeShips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArangeShips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArangeShips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField playerName;
    private seabattle.ui.ArangeShipsFieldPanel seaAreaPanel;
    // End of variables declaration//GEN-END:variables

}
