/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seabattle.ui;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import seabattle.model.ComputerPlayer;
import seabattle.model.GameModel;
import seabattle.model.events.GameOverEvent;
import seabattle.model.events.GameOverListener;
import seabattle.model.events.HitObjectEvent;
import seabattle.model.events.HitObjectListener;
import seabattle.model.events.MissObjectEvent;
import seabattle.model.events.MissObjectListener;
import seabattle.model.navigation.Cell;

/**
 *
 * @author anton
 */
public class Battle extends javax.swing.JFrame implements MissObjectListener, 
        HitObjectListener, GameOverListener{

    private GameModel _gameModel;
    private ArangeShips _arangeScreen;
    private int _seaWidth;
    private int _seaHeight;
    
    /**
     * Creates new form Battle
     */
    public Battle(ArangeShips arangeScreen, GameModel model) {
        _gameModel = model;
        _arangeScreen = arangeScreen;
        _seaWidth = model.getActiveSeaArea().width();
        _seaHeight = model.getActiveSeaArea().height();
        initComponents();
        activePanel = battlePlayerSeaPanel2;
        _gameModel.getActivePlayer().addHitListener(this);
        _gameModel.getPassivePlayer().addHitListener(this);
        _gameModel.getActivePlayer().addMissListener(this);
        _gameModel.getPassivePlayer().addMissListener(this);
        _gameModel.addGameOverListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        battlePlayerSeaPanel1 = new seabattle.ui.BattlePlayerSeaPanel(_seaHeight, _seaWidth, _gameModel.getPassivePlayer());
        battlePlayerSeaPanel2 = new seabattle.ui.BattlePlayerSeaPanel(_seaHeight, _seaWidth, _gameModel.getActivePlayer());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Battle");
        setBackground(new java.awt.Color(247, 159, 71));
        setForeground(java.awt.Color.red);
        setPreferredSize(new Dimension(60+60*_seaWidth,100+30*_seaHeight));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(_gameModel.getPassivePlayer().getName());
        jLabel1.setEnabled(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(_gameModel.getActivePlayer().getName());

        battlePlayerSeaPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        battlePlayerSeaPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                battlePlayerSeaPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout battlePlayerSeaPanel1Layout = new javax.swing.GroupLayout(battlePlayerSeaPanel1);
        battlePlayerSeaPanel1.setLayout(battlePlayerSeaPanel1Layout);
        battlePlayerSeaPanel1Layout.setHorizontalGroup(
            battlePlayerSeaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        battlePlayerSeaPanel1Layout.setVerticalGroup(
            battlePlayerSeaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        battlePlayerSeaPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        battlePlayerSeaPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                battlePlayerSeaPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout battlePlayerSeaPanel2Layout = new javax.swing.GroupLayout(battlePlayerSeaPanel2);
        battlePlayerSeaPanel2.setLayout(battlePlayerSeaPanel2Layout);
        battlePlayerSeaPanel2Layout.setHorizontalGroup(
            battlePlayerSeaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        battlePlayerSeaPanel2Layout.setVerticalGroup(
            battlePlayerSeaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(battlePlayerSeaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(battlePlayerSeaPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(372, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(battlePlayerSeaPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(battlePlayerSeaPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel2)
                    .addContainerGap(352, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void battlePlayerSeaPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_battlePlayerSeaPanel1MouseClicked
        // TODO add your handling code here:
        if (activePanel == battlePlayerSeaPanel1) {
            fireXY(evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_battlePlayerSeaPanel1MouseClicked

    private void battlePlayerSeaPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_battlePlayerSeaPanel2MouseClicked
        // TODO add your handling code here:
        if (activePanel == battlePlayerSeaPanel2) {
            fireXY(evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_battlePlayerSeaPanel2MouseClicked

    private void fireXY(int x, int y) {
        Cell target = activePanel.getCell(x, y);
        if (target != null) {
            _gameModel.getActivePlayer().fire(target);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private seabattle.ui.BattlePlayerSeaPanel battlePlayerSeaPanel1;
    private seabattle.ui.BattlePlayerSeaPanel battlePlayerSeaPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private seabattle.ui.BattlePlayerSeaPanel activePanel;
    
    private void exchangeActivePanel() {
        
        activePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        activePanel = activePanel == battlePlayerSeaPanel2 ?
                battlePlayerSeaPanel1 : battlePlayerSeaPanel2;
        jLabel1.setEnabled(!jLabel1.isEnabled());
        jLabel2.setEnabled(!jLabel2.isEnabled());
        activePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        
    }
    
    @Override
    public void missObject(MissObjectEvent e, Cell pos) {
        activePanel.repaint();
        exchangeActivePanel();
        if (_gameModel.getActivePlayer().getClass() == ComputerPlayer.class){
            _gameModel.getActivePlayer().fire(null);
        }
    }

    @Override
    public void hitObject(HitObjectEvent e, Cell pos) {
        activePanel.repaint();
    }

    @Override
    public void GameOverPerform(GameOverEvent e) {
        activePanel.repaint();
        JOptionPane.showMessageDialog(null, "Победитель: " + _gameModel.getActivePlayer().getName(), "Battle end!", JOptionPane.INFORMATION_MESSAGE);
        _arangeScreen.setVisible(true);
        _arangeScreen.requestFocus();
        _arangeScreen.requestFocusInWindow();
        this.setVisible(false);
        this.dispose();
    }
}
